<?php

/**
 * PHP version of https://github.com/Tw1ddle/geometrize-haxe/commit/e6ed1ab8c3867ac0da5bfea25ee4e7204ad286be
 * Based on PHP code generated with Haxe on this base version
 * + manual optimization&refactoring
 *
 * boot PHP utils classes and start autoload for geometrize & al
 */

if(version_compare(PHP_VERSION, '5.1.0', '<')) {
    exit('Your current PHP version is: ' . PHP_VERSION . '. Haxe/PHP generates code for version 5.1.0 or later');
} else if(version_compare(PHP_VERSION, '5.4.0', '<')) {
	trigger_error('Your current PHP version is: ' . PHP_VERSION . '. Code generated by Haxe/PHP might not work for versions < 5.4.0', E_USER_WARNING);
};


require_once __DIR__ . '/geometrize/bitmap/Bitmap.class.php';

require_once __DIR__ . '/geometrize/rasterizer/Scanline.class.php';
require_once __DIR__ . '/geometrize/rasterizer/Rasterizer.class.php';


require_once __DIR__ . '/geometrize/shape/ShapeTypes.class.php';
require_once __DIR__ . '/geometrize/shape/Shape.interface.php';
require_once __DIR__ . '/geometrize/shape/ShapeFactory.class.php';

require_once __DIR__ . '/geometrize/shape/Ellipse.class.php';
require_once __DIR__ . '/geometrize/shape/QuadraticBezier.class.php';
require_once __DIR__ . '/geometrize/shape/RotatedEllipse.class.php';
require_once __DIR__ . '/geometrize/shape/Rectangle.class.php';
require_once __DIR__ . '/geometrize/shape/RotatedRectangle.class.php';
require_once __DIR__ . '/geometrize/shape/Triangle.class.php';

require_once __DIR__ . '/geometrize/shape/Circle.class.php';
require_once __DIR__ . '/geometrize/shape/Line.class.php';



require_once __DIR__ . '/geometrize/runner/ImageRunner.class.php';

require_once __DIR__ . '/geometrize/exporter/SvgExporter.class.php';

require_once __DIR__ . '/geometrize/State.class.php';
require_once __DIR__ . '/geometrize/Model.class.php';
require_once __DIR__ . '/geometrize/Core.class.php';
