<?php

// Generated by Haxe 3.4.7
class geometrize_Model {
	/**
	 * @var int
	 */
	protected $width;

	/**
	 * @var int
	 */
	protected $height;

	/**
	 * @var geometrize_bitmap_Bitmap
	 */
	protected $target;

	/**
	 * @var geometrize_bitmap_Bitmap
	 */
	protected $current;

	/**
	 * @var geometrize_bitmap_Bitmap
	 */
	protected $buffer;

	/**
	 * @var float
	 */
	protected $score;

	public function __construct($target, $backgroundColor){
		if (!($target!==null)){
			throw new HException("FAIL: target != null");
		}
		$this->width = $target->width;
		$this->height = $target->height;
		$this->target = $target;
		$this->current = geometrize_bitmap_Bitmap::create($this->width,$this->height,$backgroundColor);
		$this->score = geometrize_Core::differenceFull($target, $this->current);

		$this->buffer = clone $this->current;
	}

	public function step($shapeTypes, $alpha, $n, $age){
		$state = geometrize_Core::bestHillClimbState($shapeTypes, $alpha, $n, $age, $this->target, $this->current, $this->buffer, $this->score);
		$results = [$this->addShape($state->shape, $state->alpha)];
		return $results;
	}

	public function addShape($shape, $alpha){
		if (!($shape!==null)){
			throw new HException("FAIL: shape != null");
		}
		$before = clone $this->current;

		$lines = $shape->rasterize();
		if (!isset($shape->color)){
			$shape->color = geometrize_Core::computeColor($this->target, $this->current, $lines, $alpha);
		}

		geometrize_rasterizer_Rasterizer::drawLines($this->current, $shape->color, $lines);
		$this->score = geometrize_Core::differencePartial($this->target, $before, $this->current, $this->score, $lines);
		$score_normalization = $before->width * $before->height * 4 * 255;
		$result = ["score" => $this->score/$score_normalization, "color" => $shape->color, "shape" => $shape];
		return $result;
	}

	public function getCurrent() {
		return $this->current;
	}

	public function getHeight() {
		return $this->height;
	}

	public function getWidth() {
		return $this->width;
	}

	function __toString(){
		return 'geometrize.Model';
	}
}
