<?php

// Generated by Haxe 3.4.7
class geometrize_runner_ImageRunner {
	public $model;

	public function __construct($inputImage, $backgroundColor){
		$this->model = new geometrize_Model($inputImage, $backgroundColor);
	}

	public function step($options){
		return $this->model->step($options['shapeTypes'], $options['alpha'], $options['candidateShapesPerStep'], $options['shapeMutationsPerStep']);
	}

	public function getImageData(){
		if (!($this->model!==null)){
			throw new HException("FAIL: model != null");
		}
		return $this->model->current;
	}

	public function __call($m, $a){
		if (isset($this->$m) && is_callable($this->$m)){
			return call_user_func_array($this->$m, $a);
		} else {
			if (isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m])){
				return call_user_func_array($this->__dynamics[$m], $a);
			} else {
				if ('toString'==$m){
					return $this->__toString();
				} else {
					throw new HException('Unable to call <' . $m . '>');
				}
			}
		}
	}

	function __toString(){
		return 'geometrize.runner.ImageRunner';
	}
}
