<?php

// Generated by Haxe 3.4.7
class geometrize_runner_ImageRunner {

	const Version = "1.0";

	/**
	 * @var geometrize_Model
	 */
	protected $model;

	public function __construct($inputImage, $backgroundColor){
		$this->model = new geometrize_Model($inputImage, $backgroundColor);
	}

	/**
	 * @param array $options
	 * @return array
	 */
	public function step($options){
		return $this->model->step($options['shapeTypes'], $options['alpha'], $options['candidateShapesPerStep'], $options['shapeMutationsPerStep']);
	}

	/**
	 * @return geometrize_bitmap_Bitmap
	 * @throws HException
	 */
	public function getImageData(){
		if (!($this->model!==null)){
			throw new HException("FAIL: model != null");
		}
		return $this->model->getCurrent();
	}

	/**
	 * @return geometrize_Model
	 */
	public function getModel() {
		return $this->model;
	}

	function __toString(){
		return 'geometrize.runner.ImageRunner';
	}
}
