<?php

// Generated by Haxe 3.4.7
class php_Lib {
	public function __construct(){}
	static function hprint($v) {
		echo(Std::string($v));
	}
	static function println($v) {
		php_Lib::hprint($v);
		php_Lib::hprint("\x0A");
	}
	function __toString() { return 'php.Lib'; }
}
