<?php

// Generated by Haxe 3.4.7
class geometrize_shape_Line extends geometrize_shape_Rectangle {

	/**
	 * @return array
	 * @throws HException
	 */
	public function rasterize(){
		if (!$this->lines){
			list($xm1, $ym1, $xm2, $ym2) = $this->getRawShapeData();

			$this->lines = [];
			if ($xm2>$xm1 or $ym2>$ym1){
				$points = [
					['x' => $xm1, 'y' => $ym1],
					['x' => $xm2, 'y' => $ym2]
				];
				$this->lines = geometrize_rasterizer_Rasterizer::scanlinesForPath($points, $this->xBound, $this->yBound);
			}
		}

		return $this->lines;
	}

	public function getType(){
		return geometrize_shape_ShapeTypes::T_LINE;
	}

	/**
	 * @return string
	 */
	public function getSvgShapeData(){
		list($xm1, $ym1, $xm2, $ym2) = $this->getRawShapeData();
		$points = [
			['x' => $xm1, 'y' => $ym1],
			['x' => $xm2, 'y' => $ym2]
		];
		return geometrize_exporter_SvgExporter::exportLines($points);
	}

	function __toString(){
		return 'geometrize.shape.Line';
	}
}
