<?php

// Generated by Haxe 3.4.7
interface geometrize_shape_Shape {
	public function rasterize();

	public function mutate();

	public function getSizeFactor();

	public function rescale($xBound, $yBound);

	public function getType();

	public function getRawShapeData();

	public function getSvgShapeData();
}
