<?php

// Generated by Haxe 3.4.7
class geometrize_shape_ShapeTypes {
	public function __construct(){
	}

	static $RECTANGLE;
	static $ROTATED_RECTANGLE;
	static $TRIANGLE;
	static $ELLIPSE;
	static $ROTATED_ELLIPSE;
	static $CIRCLE;
	static $LINE;
	static $QUADRATIC_BEZIER;

	function __toString(){
		return 'geometrize.shape.ShapeTypes';
	}
}

geometrize_shape_ShapeTypes::$RECTANGLE = 0;
geometrize_shape_ShapeTypes::$ROTATED_RECTANGLE = 1;
geometrize_shape_ShapeTypes::$TRIANGLE = 2;
geometrize_shape_ShapeTypes::$ELLIPSE = 3;
geometrize_shape_ShapeTypes::$ROTATED_ELLIPSE = 4;
geometrize_shape_ShapeTypes::$CIRCLE = 5;
geometrize_shape_ShapeTypes::$LINE = 6;
geometrize_shape_ShapeTypes::$QUADRATIC_BEZIER = 7;
