<?php

// Generated by Haxe 3.4.7
class geometrize_shape_ShapeTypes {
	public function __construct(){
	}

	const T_RECTANGLE = 0;
	const T_ROTATED_RECTANGLE = 1;
	const T_TRIANGLE = 2;
	const T_ELLIPSE = 3;
	const T_ROTATED_ELLIPSE = 4;
	const T_CIRCLE = 5;
	const T_LINE = 6;
	const T_QUADRATIC_BEZIER = 7;

	function __toString(){
		return 'geometrize.shape.ShapeTypes';
	}
}